spring:
  datasource:
    url: jdbc:h2:file:~data/db_gatravesso;MODE=MYSQL;DATABASE_TO_LOWER=TRUE
    username: sa
    password: sa
  jpa:
    database: h2
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2